### PR TITLE
Replace broken link to API reference

### PR DESCRIPTION
**Pull request by davidmerfield**
The page stored on the internet archive works OK.

### CODE REVIEW

**Comment by ChALkeR** [comment]
Not a solution. The links there don't work.

**Comment by davidmerfield** [comment]
@ChALkeR [The link](https://web.archive.org/web/20131213035158/http://coffeedoc.info/github/dropbox/dropbox-js/master/class_index.html) works. Admittedly there's no CSS but it's the best option right now.

**Comment by ChALkeR** [comment]
The links there don't work. Try opening the first class in the class index.

**Comment by davidmerfield** [comment]
@ChALkeR Ah you're quite right, a few of them aren't archived. Bummer.

**Pull request closed without merging**
