### PR TITLE
Improve handling of JS environment detection under Browserify and browse...

### PR DESCRIPTION
**Pull request by robertknight**
Depending on the environment under which Dropbox-js is used,
there will be different ways to:

 - Access web APIs like XMLHttpRequest, base64 encoding, typed arrays
   etc.
 - Export Dropbox functionality for use by other code - eg. via
   module.exports or a property on `window` or `self`
 - Import functionality for use by Dropbox-js - eg. via require()

Previously there was an assumption that Dropbox-js was running
under one of three main types of environment - a browser, Node.js
or a web worker. The code first detected one of these types of
environment and set all of the above facets accordingly.

This broke apps in hybrid environments like Browserify which provide
both the `window` object but also a Node.js-like module environment for
example.

This commit refactors environment setup to deal with each of the facets
of the environment (web API access, module export, module import)
separately.

This fixes an issue where Dropbox-js did not work in a Browserify-like environment because it assumed it was running under Node.js. In Browserify this will use 'window' as the global (so we use native XHR + Dropbox' workarounds for various XHR quirks) but still export functionality via modules.export for use in other Browserify modules.

### CODE REVIEW

**Comment by rtfeldman** [comment]
Sorry to keep pinging on this, but still hoping for a status update.

**Comment by nrw** [comment]
+1 lgtm

**Comment by joshzana** [comment]
This also enables use of dropbox.js within react-native apps, once https://github.com/facebook/react-native/pull/892 lands

**Comment by robertknight** [comment]
Thanks @joshzana - that could be very useful for a react-native project I have in mind.

**Comment by moszeed** [comment]
+1

**Comment by runn1ng** [comment]
+1

**Comment by moszeed** [comment]
maybe it helps someone else, 
i build a Promise Wrapper for dropbox.js that uses a modified Version of dropbox.js (including this Patch) to enable compatibility with Browserify.

https://www.npmjs.com/package/drbx-js

**Comment by developit** [comment]
So has anyone forked this yet to address this issue?

**Comment by robertknight** [comment]
@developit This issue is a pull request, so it includes the code I wrote to fix the problem. If look at the bottom of this thread you'll see a link to my branch on GitHub. I've been using it "in production" for a year in [Passcards](https://github.com/robertknight/passcards). See this [package.json](https://github.com/robertknight/passcards/blob/master/package.json) file and the [Makefile](https://github.com/robertknight/passcards/blob/master/Makefile#L120) for the steps I use to include and build the fork.

**Comment by developit** [comment]
Gotcha, for now I'm using `robertknight/dropbox-js#5568865764d9deab69836569a69d72d200c88293`.

**Comment by mszczepanczyk** [comment]
:thumbsup: thanks!

**Comment by bcallaars** [comment]
:shipit:

**Comment by robertknight** [comment]
Given that Dropbox now has an [official JS SDK](https://github.com/dropbox/dropbox-sdk-js) for its V2 API which supports use with module bundlers, I'm going to close this.

**Pull request closed without merging**
